//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.25 at 09:25:06 PM CEST 
//


package de.mknblch.nml.entities;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="BPM" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="BPM_QUALITY" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "TEMPO")
public class TEMPO {

    @XmlAttribute(name = "BPM")
    protected Double bpm;
    @XmlAttribute(name = "BPM_QUALITY")
    protected Integer bpmquality;

    /**
     * Gets the value of the bpm property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getBPM() {
        return bpm;
    }

    /**
     * Sets the value of the bpm property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setBPM(Double value) {
        this.bpm = value;
    }

    /**
     * Gets the value of the bpmquality property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getBPMQUALITY() {
        return bpmquality;
    }

    /**
     * Sets the value of the bpmquality property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setBPMQUALITY(Integer value) {
        this.bpmquality = value;
    }

}
